index.js
test.js

Lambda function stdout is now split on `\n` character to get the last value. This assumes the last value in stdout is the result object from the Lambda function. If it cannot be parsed, it is returned as a string. If stdout has no entries, an empty string will be returned to the caller.
Fixes #16

Fix JSON Parse Error

---

examples/module-native/package.json

There is no distinct `lambci\lambda-build` container but instead a branch of the `lambci\lambda` container per [docs](https://github.com/lambci/docker-lambda/blame/master/README.md#L55).

This example has changed since this was created

---

python3.6/build/Dockerfile

This avoids leaving /root/.cache directory with cached.
This particularly causes `serverless-python-requirements` to fail building packages.

Use --no-cache-dir when using pip install.

---

python2.7/run/runtime-mock.py
python3.6/run/runtime-mock.py

I run lambda:python3.6 with `AWS_LAMBDA_FUNCTION_TIMEOUT`
The container show me an error message. 
```
$ docker run -v "$PWD":/var/task -e AWS_LAMBDA_FUNCTION_TIMEOUT=1 lambci/lambda:python3.6
START RequestId: 9d3dab1a-855f-4f82-a5b4-73bc6a320c03 Version: $LATEST
END RequestId: 9d3dab1a-855f-4f82-a5b4-73bc6a320c03
Traceback (most recent call last):
File "/var/runtime/awslambda/bootstrap.py", line 466, in <module>
main()
File "/var/runtime/awslambda/bootstrap.py", line 462, in main
handle_event_request(request_handler, invokeid, event_body, context_objs, invoked_function_arn)
File "/var/runtime/awslambda/bootstrap.py", line 250, in handle_event_request
lambda_runtime.report_done(invokeid, errortype, result)
File "/var/runtime/awslambda/runtime.py", line 130, in report_done
billed_duration …
```

_GLOBAL_TIMEOUT is invalid type on Python 

---

python3.6/build/Dockerfile

The python3 docker image currently doesn't install `virtualenv` as the python2 image does. This PR changes the python3 docker image to install `virtualenv` as well and aligns the behavior.
Please have a look

Install virtualenv in python3 docker image

---

go1.x/build/Dockerfile

vgo is starting to replace dep in go applications. I've added this to the build image so people starting new go projects can take advantage 👍

Include vgo in the go build image

---

python3.6/build/Dockerfile

Executes `libainstall` on Python installation. It provides `/var/lang/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a`, needed to compile some packages. For exemple, uWSGI:
```
Collecting uwsgi
Downloading https://files.pythonhosted.org/packages/a2/c9/a2d5737f63cd9df4317a4acc15d1ddf4952e28398601d8d7d706c16381e0/uwsgi-2.0.17.1.tar.gz (800kB)
100% |████████████████████████████████| 808kB 9.9MB/s
Installing collected packages: uwsgi
Running setup.py install for uwsgi ... error
Complete output from command /var/lang//bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-p2ky0__w/uwsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record …
```

[FIX] python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a: No such file or directory

---

base/build/Dockerfile

After the recent release of `lambci/lambda:build-python3.6`, I've noticed the installation of system packages with YUM using `lambci/lambda:build-python3.6` doesn't work and I think eventually all other Docker images are affected as well. I need to install another system packages, mostly `devel` pkgs to install compiled Python' PYPI packages, like `pymysql`.
**The issue is in the YUM's rpmdb and the error is reproducible when trying to install any package, for example this was my case:**
`docker run -it lambci/lambda:build-python3.6 bash -c 'yum install -y freetds-devel'`
The entire operation fails with exit code `1` and displays the following error:
`Rpmdb checksum is invalid: dCDPT(pkg checksums): freetds.x86_64 0:0.91-2.3.amzn1 - u`
This unfortunately seems to be a known issue …

RPM DB broken on layered filesystems

---

dotnetcore2.0/build/Dockerfile
dotnetcore2.1/build/Dockerfile
go1.x/build/Dockerfile
java8/build/Dockerfile
nodejs4.3/build/Dockerfile
nodejs6.10/build/Dockerfile
nodejs8.10/build/Dockerfile
python2.7/build/Dockerfile
python3.6/build/Dockerfile

Upgrading from a development release to a stable release of AWS Lambda Builders

Upgrading AWS Lambda Builders to v0.0.2

---

dotnetcore2.0/build/Dockerfile
dotnetcore2.1/build/Dockerfile
go1.x/build/Dockerfile
java8/build/Dockerfile
nodejs4.3/build/Dockerfile
nodejs6.10/build/Dockerfile
nodejs8.10/build/Dockerfile
python2.7/build/Dockerfile
python3.6/build/Dockerfile

Release notes: https://github.com/awslabs/aws-lambda-builders/releases/tag/0.0.3
This release supports Python 3.7 runtime. It also adds a fix for the case when the Python3.6 image does not have `wheel` dependency. `wheel` is required to build modules that don't have prebuilt artifacts published to PyPi.

Upgrading AWS Lambda Builders to v0.0.3

---

dotnetcore2.0/run/MockBootstraps/DebuggerExtensions.cs
dotnetcore2.0/run/MockBootstraps/Program.cs
dotnetcore2.1/run/MockBootstraps/DebuggerExtensions.cs
dotnetcore2.1/run/MockBootstraps/Program.cs

#125 - issue, that requests .NET Core 2.0 / 2.1 debugging support
* Added `DebuggerExtensions` class which enables waiting for the debugger to attach in the loop, inspecting `Debugger.IsAttached` property with interval (50ms). Also it has 10 minutes timeout, after it, function will continue executing without debugging;
* Added `--debugger-spin-wait` flag handling, if it supplied as an argument, then, we will use `DebuggerExtensions.TryWaitForAttaching` to wait for the debugger before proceeding to execution;
* Added `try / catch` block for all body of `Main` to prevent user from hanging on `External Code Exception` while debugging.
I've closed #127 as it had a lot of unnecessary stuff. Now this PR has only required changes, to proceed with #125.

Wait for debugger flag for .NET Core 2.0 / 2.1 implementation

---

dotnetcore2.0/build/Dockerfile
dotnetcore2.1/build/Dockerfile
go1.x/build/Dockerfile
java8/build/Dockerfile
nodejs4.3/build/Dockerfile
nodejs6.10/build/Dockerfile
nodejs8.10/build/Dockerfile
provided/build/Dockerfile
python2.7/build/Dockerfile
python3.6/build/Dockerfile
python3.7/build/Dockerfile
ruby2.5/build/Dockerfile

This version supports building Node.js functions through NPM.
Release notes: https://github.com/awslabs/aws-lambda-builders/releases/tag/v0.0.4

Upgrading AWS Lambda Builders to v0.0.4

---

ruby2.5/build/Dockerfile

Hi, I'm the maintainer of RubyGems. We are removing `--no-ri` and `--no-rdoc` options at RubyGems 3.0. Please use `--no-document` instead of them.

Use --document option instead of --ri and --rdoc

---

dotnetcore2.0/build/Dockerfile
dotnetcore2.1/build/Dockerfile
go1.x/build/Dockerfile
java8/build/Dockerfile
nodejs4.3/build/Dockerfile
nodejs6.10/build/Dockerfile
nodejs8.10/build/Dockerfile
provided/build/Dockerfile
python2.7/build/Dockerfile
python3.6/build/Dockerfile
python3.7/build/Dockerfile
ruby2.5/build/Dockerfile

This version supports building Ruby functions through bundler.
Release notes: https://github.com/awslabs/aws-lambda-builders/releases/tag/v0.0.5

Upgrading AWS Lambda Builders to v0.0.5

---

go1.x/run/aws-lambda-mock.go

Configure Delve API version via flags, which has a default value of '1' for backwards compatibility.
There is now a lot of interest in running the Delve debugger with API version **'2'** [Debugging go functions works with VS Code but not Goland](https://github.com/awslabs/aws-sam-cli/issues/886).
We are all now aware VSC and other IDEs support this newer Devle API version.
This pull request is addressing the out-standing comments left within the PR (#131) raised, which have been unaddressed for 3+ months.

bump Go debugger Delve API via flags

---

dotnetcore2.1/build/Dockerfile

Adding the environment variable `DOTNET_ROOT` and the tools path enables use of .NET Global Tools.
Most useful is the `Amazon.Lambda.Tools` global tool, enabling commands beginning with `dotnet lambda`, such as `dotnet lambda package`. I considered installing this tool by default, but decided it may be too aggressive. If that sounds desirable, I can add another commit to this PR.

Enables Use of .NET Global Tools in Build Image

---

dotnetcore2.1/build/Dockerfile

...and also correct a bug related to setting the environment
Fixes bug introduced in https://github.com/lambci/docker-lambda/pull/156.

Install Amazon Lambda Global Tools by Default

---

base/native-test.sh
nodejs4.3/run/Dockerfile

I'm having issues running `node` in the Node v4.3 Docker image:
```shell
Fetching lambci/lambda:nodejs4.3 Docker container image......
2019-07-26 12:33:23 Mounting <PATH> as /var/task:ro,delegated inside runtime container
Traceback (most recent call last):
File "/usr/local/bin/sam", line 10, in <module>
sys.exit(cli())
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return …
```

Fix Node v4.3 entrypoint

---

dotnetcore2.1/build/Dockerfile

Some of my teams have reported that this drift is preventing the `sam build` command from working in their CI/CD scripts.

Update Amazon.Lambda.Tools Version to Latest

---

go1.x/build/Dockerfile

This pull request bumps up the Golang version from `1.12.9` to latest `1.13.1` for `lambci/lambda:build-go1.x`.

Update Golang version to 1.13.1 in builder Dockerfile

---

dotnetcore2.0/run/MockBootstraps/MockRuntime.cs
dotnetcore2.1/run/MockBootstraps/MockRuntime.cs
java8/run/lambda-runtime-mock/src/main/java/lambdainternal/LambdaRuntime.java
nodejs4.3/run/awslambda-mock.js
nodejs6.10/run/awslambda-mock.js
nodejs8.10/run/awslambda-mock.js
provided/run/go.mod
provided/run/go.sum
provided/run/init.go
python2.7/run/runtime_mock.py
python3.6/run/runtime_mock.py

Addresses #229 
Can either send SIGHUP to the bootstrap process:
```sh
docker kill --signal=SIGHUP <container_id>
```
Or, if you pass `DOCKER_LAMBDA_WATCH=1` as an env var, then any changes to files in `/var/task` or `/opt` (ie, your handler directory and any layers you have mounted) will trigger the bootstrap to be killed (and it will cold start again on next invocation)
```
docker run --rm -v "$PWD":/var/task:ro,delegated \
-e DOCKER_LAMBDA_STAY_OPEN=1 \
-e DOCKER_LAMBDA_WATCH=1 \
-p 9001:9001 \
lambci/lambda:provided handler
```
Works with the following runtimes: `provided`, `nodejs10.x`, `nodejs12.x`, `python3.7`, `python3.8` `ruby2.5`, `java11`
The other runtimes will need another strategy that restarts the root process (the easiest will be to utilize `docker run --restart …

Add file watching

---

provided/run/init.go

This PR is to help users that need to start more than on docker containers in network mode `host`. With server listening in the hardcoded port 9001, it's not possible. So, my suggestion is to use the same variable to `DOCKER_LAMBDA_API_PORT` to the server.
**My issue:** I need to trigger more than one lambda at the same time and my network mode needs to be `host`. The first lambda run and starts listening on port 9001. When the second lambda run, the port 9001 is already in use throwing an error.
**My suggestion** is to make the server port customizable, so I can run the lambdas setting different port values.
**Steps to reproduce**
* Terminal 1
```
$ nc -l -p 9001
```
* Terminal 2
```
$ CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e …
```

Changing lambda API and server to listen in the same port

---

ruby2.5/build/Dockerfile

Currently the latest version of `bundler` will be installed into the docker image upon any build, causing bundler to get out of sync with the lambda environment.
Version `2.0.2` was determined based on the output of the following (very basic) lambda code:
```
require 'json'
require 'bundler'
def lambda_handler(event:, context:)
puts "#{Bundler::VERSION}"
{ statusCode: 200, body: JSON.generate('Hello from Lambda!') }
end
```

Set bundler to a specific version that matches what is in AWS

---

ruby2.5/build/Dockerfile
ruby2.7/build/Dockerfile

This change suppress the "Don't run Bundler as root" warning, this config it's used by the official [ruby dockerfile as well](https://github.com/docker-library/ruby/blob/master/2.5/alpine3.11/Dockerfile#L127).
```
Don't run Bundler as root. Bundler can ask for sudo if it is needed,
and installing your bundle as root will break this application for all non-root users on this machine.
```

set BUNDLE_SILENCE_ROOT_WARNING=1 for all ruby container

---

base/build-2/Dockerfile
base/build/Dockerfile
base/publish-all.sh
dotnetcore2.0/build/Dockerfile
dotnetcore2.1/build/Dockerfile
dotnetcore3.1/build/Dockerfile
go1.x/build/Dockerfile
java11/build/Dockerfile
java8/build/Dockerfile
nodejs10.x/build/Dockerfile
nodejs12.x/build/Dockerfile
nodejs4.3/build/Dockerfile
nodejs6.10/build/Dockerfile
nodejs8.10/build/Dockerfile
provided/build/Dockerfile
python3.6/build/Dockerfile
python3.7/build/Dockerfile
python3.8/build/Dockerfile
ruby2.5/build/Dockerfile
ruby2.7/build/Dockerfile

- Add /root/.local/bin to PATH
- Add pipx to base build images
- Update aws-lambda-builders to 1.0.0
- Update dotnetcore3.1 build SDK to 3.1.302
- Addresses discussion in #296

Use pipx for all global python binaries

---

provided/run/init.go

https://aws.amazon.com/ko/blogs/aws/new-for-aws-lambda-1ms-billing-granularity-adds-cost-savings/
Lambda billed duration was updated by 1ms, but I found the log was not applied yet.

fix(log): apply billed duration by 1ms
